name: CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  S3LambdaUploadTest:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: GitHubActionsDeploySession
          aws-region: ${{ secrets.AWS_REGION }}
      # Upload a file to AWS s3
      - name: Copy README.md to S3
        run: |
          BUCKET_NAME=${{ secrets.BUCKET_NAME }}
          aws s3 sync ./fourtooncookie-diaryimage-ai-apply-lambda s3://$BUCKET_NAME/lambda --delete
